[tool.poetry]
name = "buffering-queue-logger"
version = "0.2.0"
description = "Helpers for sending logs to a destination in batches using a buffer in a queue alongside any Python app."
authors = ["Jeremy Epstein <jazepstein@gmail.com>"]
homepage = "https://github.com/Jaza/buffering-queue-logger"
readme = "README.md"
license = "Apache-2.0"
packages = [{include = "buffering_queue_logger"}]

[tool.poetry.dependencies]
python = ">=3.10,<4"
requests = "^2.28.2"


[tool.poetry.group.dev.dependencies]
pytest = "*"
black = "*"
flake8 = "*"
mypy = "*"
isort = "*"
pytest-cov = "*"
autoflake = "*"
bandit = {extras = ["toml"], version = "*"}
types-requests = "^2.28.11.17"

[tool.mypy]
ignore_missing_imports = true

[tool.isort]
profile = "black"
lines_after_imports = 2

[tool.bandit]
skips = ["B101"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
